# Generated by Django 4.2.7 on 2023-11-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('username', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('conform_pass', models.CharField(max_length=122)),
            ],
        ),
    ]
